[phases.setup]
nixPkgs = ["ffmpeg", "gcc"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
cmds = [
  "apt-get update && apt-get install -y ffmpeg"
]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port 8000"
